### ISSUE TITLE
Invoice Template via Google Cloud Functions

### ISSUE THREAD

**Issue by besnikh** [edisonneza/jspdf-invoice-template#10]
Hi again,
While I love your package I was trying to get off the load from browser and create background functions using Google Cloud Functions to generate new Invoices and thus update the Invoice URL in database.

The problem I am facing with my test script is that I get this error 

`Error: Automatic publicPath is not supported in this browser`

My function is nothing fancy, a simple exppressjs route

```
app.get('/generateInvoice', (req, res) => {
 const jsPDFInvoiceTemplate = require("jspdf-invoice-template");
 const props = {
  outputType: 'blob',
  ...otherProps
  }
  const pdfCreated = jsPDFInvoiceTemplate(props);
  const blob = pdfCreated.blob
  res.send(blob)
})
```

This is working perfectly in Browser but when I try on Cloud Function I got that error. 

```
Error: Automatic publicPath is not supported in this browser
    at /home/besnik/Desktop/Nap Inc/functions/node_modules/jspdf-invoice-template/dist/index.js:2:351320
    at /home/besnik/Desktop/Nap Inc/functions/node_modules/jspdf-invoice-template/dist/index.js:2:351462
    at /home/besnik/Desktop/Nap Inc/functions/node_modules/jspdf-invoice-template/dist/index.js:2:352242
    at /home/besnik/Desktop/Nap Inc/functions/node_modules/jspdf-invoice-template/dist/index.js:2:81
    at Object.<anonymous> (/home/besnik/Desktop/Nap Inc/functions/node_modules/jspdf-invoice-template/dist/index.js:2:221)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
```

If I could manage to make it work, I would share the function here as well for others :) 

Cheers,

**Comment by edisonneza** [comment]
Hey man,
   sorry, I can't help with this issue. 
   
But as I saw briefly I suggest trying adding _**publicPath: ''**_ inside the _**output**_ prop in webpack.config.js of my package. 

```
module.exports = {
  mode: 'production',
  entry: './src/index.js',
  output: {
    path: path.resolve('dist'),
    filename: 'index.js',
    library: "jsPDFInvoiceTemplate",
    libraryTarget: 'umd',
    globalObject: 'this',
    publicPath: ''
  }
  ...others
}
```

Hope it helps.
If yes, let me know in order to update the package.

Thanks!

**Comment by edisonneza** [comment]
You can reopen it if something.
